```{r setup-appendix, include=FALSE}
knitr::opts_knit$set(root.dir = 'C:/Users/matth/Climate_and_Health/bookdown_project')
```

# Appendix

## Survey Data Generation

From the Open Database of Hospitals, only facilities designated as "Hospitals" were selected to limit the final dataframe size and ease the volume of calculations in later steps. Survey dates were assigned randomly using a set seed for reproducibility. 

```{r sample-data-generation, eval=FALSE}
#generation of data based on entries in the hospital data 
#if there are 20 hospitals, make 20 random months for survey between 1 and 12 and random years choosing between 2016 and 2020
#https://www150.statcan.gc.ca/n1/en/pub/13-26-0001/2020001/ODHF_v1.1.zip
#make sure the latitude and longitude columns exist and that there is an id column as well
#set a random seed
set.seed(933)
#read in the raw data
odhf <- read.csv("./data/odhf_v1.1.csv")
#create an id list
odhf$hospital_id <- 1:nrow(odhf)
#can only use valid lat/long locations
odhf_valid <- odhf[!is.na(odhf[["latitude"]]) & 
                             !is.na(odhf[["longitude"]]), ]
odhf_valid <- odhf_valid %>% filter(odhf_facility_type=="Hospitals") %>%  select(c("latitude", "longitude", "facility_name", "odhf_facility_type", "hospital_id", "postal_code"))
#strip spaces from postal code
odhf_valid$postal_code <- gsub(" ", "", odhf_valid$postal_code)
odhf_valid <- odhf_valid %>% rename(postalcode = postal_code)
#randomization
odhf_valid[[survey_month_col]] <- sample(1:12, size = nrow(odhf_valid), replace = TRUE)
odhf_valid[[survey_year_col]] <- sample(2018:2021, size=nrow(odhf_valid), replace = TRUE)
#change names
setnames(odhf_valid, c("latitude", "longitude"), c("lat","long"))
#write for reading in elsewhere
write.csv(odhf_valid, "./data/odhf_hospitals.csv")
```